version: "3.7"

networks:
  db-net:
    name: db-net
    driver: bridge

volumes:
  pg-data:
  neo4j-data:
  portainer-data:

secrets:
  postgres-root-password:
    file: ${PWD}/docker/local/postgres_root_password.txt

services:
  # https://hub.docker.com/_/postgres
  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-root-password
    ports:
      - 5434:5432
    secrets:
      - postgres-root-password
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - db-net

  # https://neo4j.com/developer/docker/#neo4j-docker
  neo4j:
    image: neo4j:4.2
    env_file:
      - ${PWD}/docker/local/neo4j.env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    networks:
      - db-net

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - db-net
